# version: "3.8"                       deprecated

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
    ports:
      - 8081:8081

  nodeapp:
    build:
      dockerfile: Dockerfile
    image: nodeapp:v0.1
    ports:
      - 5001:5001
